// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// LOGADD.H
// 
//

#ifndef __LOGREPDEFS_H__
#define __LOGREPDEFS_H__

const TUid KUidLogengRepository = { 0x101f401d }; //The repository for Log engine
const TInt KMaxLogSizeRepKey = 1;
const TInt KMaxRecentLogSizeRepKey = 2;
const TInt KMaxEventAgeRepKey = 3;
const TInt KContactMatchCountRepKey = 4;
const TInt KContactNameFormatRepKey = 5;

#endif
