@rem
@rem Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
@rem All rights reserved.
@rem This component and the accompanying materials are made available
@rem under the terms of "Eclipse Public License v1.0"
@rem which accompanies this distribution, and is available
@rem at the URL "http://www.eclipse.org/legal/epl-v10.html".
@rem
@rem Initial Contributors:
@rem Nokia Corporation - initial contribution.
@rem
@rem Contributors:
@rem
@rem Description:
@rem

T_SQLENVCREATE.EXE
T_SQLITE.EXE
T_SQLAPI.EXE
T_SQLAPI2.EXE
T_SQLPANIC.EXE
T_SQLLANG.EXE
T_SQLOOM1.EXE
T_SQLOOM2.EXE
T_SQLOOM3.EXE
T_SQLOOM4.EXE
T_SQLMULTI.EXE
T_SQLCOLLATE.EXE
T_SQLTRANS.EXE
T_SQLLOAD.EXE
T_SQLGETFIRSTSTMT.EXE
T_SQLSECURITY1.EXE
T_SQLSECURITY2.EXE
T_SQLSECURITY3.EXE
T_SQLSECURITY4.EXE
T_SQLSECURITY5.EXE
T_SQLATTACH.EXE
T_SQLPERFORMANCE.EXE
T_SQLPERFORMANCE2.EXE
T_SQLPERFORMANCE3.EXE
T_SQLPERFORMANCE4.EXE
T_SQLOOD.EXE
T_SQLOSLAYER.EXE
T_SQLDEFECT.EXE
T_SQLDEFECT2.EXE
T_SQLPRIVCAGE.EXE
T_SQLBADCLIENT.EXE
T_SQLBUR.EXE
T_SQLSCALARFULLSELECT.EXE
T_SQLFSERR.EXE
T_SQLCONFIG.EXE
T_SQLCONFIGFILE.EXE
T_SQLDBCONFIGFILE.EXE
T_SQLCOMPACT1.EXE
T_SQLCOMPACT2.EXE
T_SQLCOMPACT3.EXE
T_SQLCOMPACT4.EXE
T_SQLBLOB.EXE
T_SQLFILEBUF64.EXE
T_SQLAUTHORIZER.EXE
T_SQLENVDESTROY.EXE
